### ISSUE TITLE
Standardize build configuration schema

### ISSUE THREAD

**Issue by huddlej** [nextstrain/janus#2]
Define build configuration to support all reasonable combinations of flu, zika, ebola, and other virus builds. An example of a previous YAML schema is shown below (from `datasets.yaml`). This should mirror `datasets.js` used by auspice in that the same information that is required to build the sites could also be used to build the user interface.

```yaml
virus:
  - flu:
      lineage:
      - h3n2:
         duration:
          - 3y
          - 6y
          - 12y
      - h1n1pdm:
          duration:
          - 3y
          - 6y
          - 12y
      - vic:
          duration:
          - 3y
          - 6y
          - 12y
      - yam:
          duration:
          - 3y
          - 6y
          - 12y
  - ebola
  - zika
```

Data considerations:

  * Flu has "lineages", dengue has "serotypes", and zika and ebola have neither of these
  * Only flu and dengue have titers
  * Different sites need to be built for public and private display

Design considerations:

  * Configuration(s) should be in JSON format to maintain consistency with the rest of the nextstrain projects
  * Configs have to work with Snakemake
  * Choice between "one config per virus" or "one config for all viruses" might affect ultimate design
